In [ ]:
%load_ext autoreload
%autoreload 2

from trees.experiment import single_run
from trees.causal_tree import CT, CTP
from trees.causal_forest import CF, CFT
from trees.scanners import *

In [ ]:
single_run(CT, GreedyScore)

100%|██████████| 102/102 [00:00<00:00, 13654.38it/s]

[CT on D (GreedyScore)] Offline time: 0.09
User condition: feature_6 > -0.203 Selectivity: 0.584
[CT on D (GreedyScore)] Online time: 0.01, Total Splits: 102, Valid: 58
[GreedyScore] get topK score: 0.79 in 0.0s

,id,condition,combined,features,t_est,T0,T1,depth,algorithm,rows,total_options,validate_time,t,scan_method,scan_time,valid_options,overlap,score
0,98,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (1.836, 3.728), 'feature_4': (-3...",3,5.437,1.42,6.86,6,CT on D (GreedyScore),47,102,0.01,3.701,GreedyScore,0.0,58,0.288788,0.855606
1,97,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (1.836, 3.728), 'feature_4': (-3...",4,4.474,0.75,5.23,7,CT on D (GreedyScore),44,102,0.01,2.750,GreedyScore,0.0,58,0.182497,0.820192
2,13,feature_0 <= -1.656 AND feature_8 > 0.684 AND ...,"{'feature_0': (-4.295, -1.656), 'feature_8': (...",2,4.295,3.88,-0.41,3,CT on D (GreedyScore),39,102,0.01,1.444,GreedyScore,0.0,58,0.000000,0.894979
3,74,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (-0.41, 0.901), 'feature_1': (0....",3,3.723,0.64,4.37,6,CT on D (GreedyScore),94,102,0.01,1.883,GreedyScore,0.0,58,0.276757,0.703998
4,72,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (-0.41, 0.901), 'feature_1': (-0...",5,3.074,0.66,3.73,8,CT on D (GreedyScore),54,102,0.01,1.063,GreedyScore,0.0,58,0.194527,0.685429

In [ ]:
single_run(CT, Exhaustive)

100%|██████████| 102/102 [00:00<00:00, 13966.86it/s]

[CT on D (Exhaustive)] Offline time: 0.09
User condition: feature_6 > -0.203 Selectivity: 0.584
[CT on D (Exhaustive)] Online time: 0.01, Total Splits: 102, Valid: 58

100%|██████████| 658008/658008 [00:04<00:00, 158771.73it/s]

[Exhaustive] get topK score: 0.81 in 4.15s

,id,condition,combined,features,t_est,T0,T1,depth,algorithm,rows,total_options,validate_time,t,scan_method,scan_time,valid_options,overlap,score
0,98,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (1.836, 3.728), 'feature_4': (-3...",3,5.437,1.42,6.86,6,CT on D (Exhaustive),47,102,0.01,3.701,Exhaustive,4.15,58,0.178697,0.910652
1,97,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (1.836, 3.728), 'feature_4': (-3...",4,4.474,0.75,5.23,7,CT on D (Exhaustive),44,102,0.01,2.750,Exhaustive,4.15,58,0.182497,0.820192
2,13,feature_0 <= -1.656 AND feature_8 > 0.684 AND ...,"{'feature_0': (-4.295, -1.656), 'feature_8': (...",2,4.295,3.88,-0.41,3,CT on D (Exhaustive),39,102,0.01,1.444,Exhaustive,4.15,58,0.000000,0.894979
3,72,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (-0.41, 0.901), 'feature_1': (-0...",5,3.074,0.66,3.73,8,CT on D (Exhaustive),54,102,0.01,1.063,Exhaustive,4.15,58,0.027860,0.768763
4,76,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (0.901, 1.836)}",1,1.924,1.08,3.00,4,CT on D (Exhaustive),919,102,0.01,2.097,Exhaustive,4.15,58,0.000000,0.676936

In [ ]:
single_run(CT, GreedyCATE)

100%|██████████| 150/150 [00:00<00:00, 7877.81it/s]

[CT on D (GreedyCATE)] Offline time: 0.1
User condition: feature_4 > -0.054 Selectivity: 0.5218
[CT on D (GreedyCATE)] Online time: 0.03, Total Splits: 150, Valid: 146
[GreedyCATE] get topK score: 0.78 in 0.0s

,id,condition,combined,features,t_est,T0,T1,depth,algorithm,rows,total_options,validate_time,t,scan_method,scan_time,valid_options,overlap,score
0,121,feature_3 > -0.969 AND feature_0 > 0.15 AND fe...,"{'feature_3': (-0.969, 3.246), 'feature_0': (0...",7,5.471,-2.28,3.19,8,CT on D (GreedyCATE),31,150,0.03,1.272,GreedyCATE,0.0,146,0.313416,0.843292
1,42,feature_3 <= -0.969 AND feature_8 > -0.584 AND...,"{'feature_3': (-1.83, -0.969), 'feature_8': (-...",3,4.586,-0.12,4.47,4,CT on D (GreedyCATE),27,150,0.03,2.911,GreedyCATE,0.0,146,0.149257,0.844490
2,103,feature_3 > -0.969 AND feature_0 <= 0.15 AND f...,"{'feature_3': (-0.969, 3.246), 'feature_0': (-...",4,4.341,0.81,5.15,5,CT on D (GreedyCATE),30,150,0.03,1.914,GreedyCATE,0.0,146,0.145482,0.823987
3,4,feature_3 <= -0.969 AND feature_8 <= -0.584 AN...,"{'feature_3': (-3.726, -0.969), 'feature_8': (...",3,2.987,0.38,3.37,4,CT on D (GreedyCATE),42,150,0.03,1.520,GreedyCATE,0.0,146,0.173490,0.686240
4,77,feature_3 > -0.969 AND feature_0 <= 0.15 AND f...,"{'feature_3': (0.32, 3.246), 'feature_0': (-1....",4,2.638,3.70,1.06,8,CT on D (GreedyCATE),28,150,0.03,0.455,GreedyCATE,0.0,146,0.122426,0.679876

In [ ]:
single_run(CTP, GreedyScore)

[CT on P (GreedyScore)] Offline time: 0.0
User condition: feature_6 > -0.203 Selectivity: 0.584

100%|██████████| 110/110 [00:00<00:00, 11216.35it/s]

[CT on P (GreedyScore)] Online time: 0.07, Total Splits: 110, Valid: 102
[GreedyScore] get topK score: 0.81 in 0.0s

,id,condition,combined,features,t_est,T0,T1,depth,algorithm,rows,total_options,validate_time,t,scan_method,scan_time,valid_options,overlap,score
0,98,feature_0 > 0.172 AND feature_1 > -1.881 AND f...,"{'feature_0': (0.172, 1.804), 'feature_1': (1....",4,4.965,0.51,5.47,8,CT on P (GreedyScore),98,110,0.02,2.631,GreedyScore,0.0,102,0.332805,0.833598
1,108,feature_0 > 0.172 AND feature_1 > -1.881 AND f...,"{'feature_0': (1.804, 3.728), 'feature_1': (-1...",4,4.716,0.97,5.68,5,CT on P (GreedyScore),91,110,0.02,3.066,GreedyScore,0.0,102,0.239789,0.855030
2,60,feature_0 <= 0.172 AND feature_0 > -1.769 AND ...,"{'feature_0': (-0.677, 0.172), 'feature_1': (1...",4,4.102,-0.62,3.48,6,CT on P (GreedyScore),51,110,0.02,1.499,GreedyScore,0.0,102,0.322947,0.751618
3,6,feature_0 <= 0.172 AND feature_0 <= -1.769 AND...,"{'feature_0': (-4.295, -2.077), 'feature_5': (...",2,3.562,1.81,-1.76,4,CT on P (GreedyScore),50,110,0.02,1.577,GreedyScore,0.0,102,0.001732,0.857845
4,106,feature_0 > 0.172 AND feature_1 > -1.881 AND f...,"{'feature_0': (0.172, 1.804), 'feature_1': (0....",5,4.275,1.05,5.32,8,CT on P (GreedyScore),49,110,0.02,2.051,GreedyScore,0.0,102,0.397201,0.731913

In [ ]:
single_run(CTP, Exhaustive)

[CT on P (Exhaustive)] Offline time: 0.0
User condition: feature_6 > -0.203 Selectivity: 0.584

100%|██████████| 110/110 [00:00<00:00, 10900.73it/s]

[CT on P (Exhaustive)] Online time: 0.07, Total Splits: 110, Valid: 102

100%|██████████| 13019909/13019909 [01:24<00:00, 154502.16it/s]

[Exhaustive] get topK score: 0.84 in 84.27s

,id,condition,combined,features,t_est,T0,T1,depth,algorithm,rows,total_options,validate_time,t,scan_method,scan_time,valid_options,overlap,score
0,98,feature_0 > 0.172 AND feature_1 > -1.881 AND f...,"{'feature_0': (0.172, 1.804), 'feature_1': (1....",4,4.965,0.51,5.47,8,CT on P (Exhaustive),98,110,0.02,2.631,Exhaustive,84.27,102,0.188706,0.905647
1,108,feature_0 > 0.172 AND feature_1 > -1.881 AND f...,"{'feature_0': (1.804, 3.728), 'feature_1': (-1...",4,4.716,0.97,5.68,5,CT on P (Exhaustive),91,110,0.02,3.066,Exhaustive,84.27,102,0.198213,0.875818
2,60,feature_0 <= 0.172 AND feature_0 > -1.769 AND ...,"{'feature_0': (-0.677, 0.172), 'feature_1': (1...",4,4.102,-0.62,3.48,6,CT on P (Exhaustive),51,110,0.02,1.499,Exhaustive,84.27,102,0.221217,0.802483
3,6,feature_0 <= 0.172 AND feature_0 <= -1.769 AND...,"{'feature_0': (-4.295, -2.077), 'feature_5': (...",2,3.562,1.81,-1.76,4,CT on P (Exhaustive),50,110,0.02,1.577,Exhaustive,84.27,102,0.001732,0.857845
4,47,feature_0 <= 0.172 AND feature_0 > -1.769 AND ...,"{'feature_0': (-0.081, 0.172), 'feature_1': (-...",3,3.161,1.20,4.37,6,CT on P (Exhaustive),52,110,0.02,0.984,Exhaustive,84.27,102,0.109796,0.763430

In [ ]:
single_run(CFT, GreedyScore)

100%|██████████| 258/258 [00:00<00:00, 4757.16it/s]

[CF SingleTree (GreedyScore)] Offline time: 7.43
User condition: feature_5 <= 0.665 Selectivity: 0.7458
[CF SingleTree (GreedyScore)] Online time: 0.04, Total Splits: 258, Valid: 255
[GreedyScore] get topK score: 0.87 in 0.0s

,id,condition,combined,features,t_est,depth,algorithm,rows,total_options,validate_time,t,scan_method,scan_time,valid_options,overlap,score
0,223,feature_0 > 0.076 AND feature_0 <= 1.597 AND f...,"{'feature_0': (0.986, 1.597), 'feature_1': (1....",3,2.357,7,CF SingleTree (GreedyScore),24,258,0.04,3.242,GreedyScore,0.0,255,0.076269,0.863125
1,237,feature_0 > 0.076 AND feature_0 > 1.597 AND fe...,"{'feature_0': (1.597, 1.834), 'feature_1': (0....",2,2.352,5,CF SingleTree (GreedyScore),29,258,0.04,2.901,GreedyScore,0.0,255,0.080706,0.860055
2,248,feature_0 > 0.076 AND feature_0 > 1.597 AND fe...,"{'feature_0': (1.984, 3.728), 'feature_1': (-0...",3,2.704,6,CF SingleTree (GreedyScore),56,258,0.04,3.415,GreedyScore,0.0,255,0.120386,0.900140
3,241,feature_0 > 0.076 AND feature_0 > 1.597 AND fe...,"{'feature_0': (1.834, 1.975), 'feature_1': (-4...",2,2.287,5,CF SingleTree (GreedyScore),24,258,0.04,2.224,GreedyScore,0.0,255,0.000000,0.889343
4,235,feature_0 > 0.076 AND feature_0 > 1.597 AND fe...,"{'feature_0': (1.721, 1.834), 'feature_1': (-0...",2,2.239,6,CF SingleTree (GreedyScore),23,258,0.04,2.476,GreedyScore,0.0,255,0.082610,0.839866

In [ ]:
# single_run(CFT, scanner=Exhaustive) # Nope 4:36:09

In [ ]:
single_run(CF, GreedyScore)

100%|██████████| 4950/4950 [00:20<00:00, 242.38it/s]

[CF (GreedyScore)] Offline time: 24.2
User condition: feature_5 <= 0.665 Selectivity: 0.7458
[CF (GreedyScore)] Online time: 0.74, Total Splits: 4950, Valid: 4392
[GreedyScore] get topK score: 0.82 in 0.14s

,id,condition,combined,features,t_est,depth,algorithm,rows,total_options,validate_time,t,scan_method,scan_time,valid_options,overlap,score
0,2383,feature_0 > 0.418 AND feature_0 <= 1.672 AND f...,"{'feature_0': (0.418, 1.672), 'feature_1': (1....",2,4.381,4,CF (GreedyScore),111,4950,0.74,2.654,GreedyScore,0.02,4392,0.098631,0.827707
1,1115,feature_0 > 0.101 AND feature_1 > 0.331 AND fe...,"{'feature_0': (0.101, 3.728), 'feature_1': (0....",4,4.811,5,CF (GreedyScore),97,4950,0.74,2.165,GreedyScore,0.02,4392,0.230249,0.798903
2,2354,feature_0 <= 0.418 AND feature_1 > -0.072 AND ...,"{'feature_0': (-4.295, 0.418), 'feature_1': (-...",5,4.484,8,CF (GreedyScore),100,4950,0.74,0.612,GreedyScore,0.02,4392,0.208636,0.781568
3,773,feature_0 > 0.111 AND feature_0 > 1.967 AND fe...,"{'feature_0': (1.967, 3.728), 'feature_3': (-0...",2,5.810,3,CF (GreedyScore),113,4950,0.74,3.152,GreedyScore,0.02,4392,0.245067,0.877466
4,3342,feature_0 > 0.931 AND feature_1 <= 1.099 AND f...,"{'feature_0': (0.931, 1.074), 'feature_1': (-4...",3,4.039,5,CF (GreedyScore),113,4950,0.74,1.666,GreedyScore,0.02,4392,0.053750,0.820715