In [12]:
%load_ext autoreload
%autoreload 2

from trees.experiment import debug
from trees.causal_tree import CT, CTP
from trees.causal_forest import CF, CFT
from trees.scanners import Exhaustive, Greedy

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [15]:
debug(CT, Greedy)

100%|██████████| 102/102 [00:00<00:00, 14584.41it/s]

[CT on D (Greedy)] Offline time: 0.09
User condition: feature_6 > -0.203 Selectivity: 0.584
[CT on D (Greedy)] Online time: 0.01, Total Splits: 102, Valid: 58
Replacing 0.6412083869781129 with 0.650069206781584
New min score 0.6762636282121279
Replacing 0.6762636282121279 with 0.6769358101894427
New min score 0.6769358101894427
Total score: 0.8097947305841862
[Greedy] get topK in 0.0

,id,condition,combined,features,t_est,T0,T1,depth,algorithm,rows,total_options,validate_time,t,scan_method,scan_time,valid_options,overlap,score
0,98,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (1.836, 3.728), 'feature_4': (-3...",3,5.437,1.42,6.86,6,CT on D (Greedy),47,102,0.01,3.701,Greedy,0.0,58,0.276757,0.861621
1,97,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (1.836, 3.728), 'feature_4': (-3...",4,4.474,0.75,5.23,7,CT on D (Greedy),44,102,0.01,2.750,Greedy,0.0,58,0.166667,0.828107
2,13,feature_0 <= -1.656 AND feature_8 > 0.684 AND ...,"{'feature_0': (-4.295, -1.656), 'feature_8': (...",2,4.295,3.88,-0.41,3,CT on D (Greedy),39,102,0.01,1.444,Greedy,0.0,58,0.000000,0.894979
3,74,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (-0.41, 0.901), 'feature_1': (0....",3,3.723,0.64,4.37,6,CT on D (Greedy),94,102,0.01,1.883,Greedy,0.0,58,0.110091,0.787331
4,76,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (0.901, 1.836)}",1,1.924,1.08,3.00,4,CT on D (Greedy),919,102,0.01,2.097,Greedy,0.0,58,0.000000,0.676936

In [16]:
debug(CT, Exhaustive)

100%|██████████| 102/102 [00:00<00:00, 13835.87it/s]

[CT on D (Exhaustive)] Offline time: 0.09
User condition: feature_6 > -0.203 Selectivity: 0.584
[CT on D (Exhaustive)] Online time: 0.01, Total Splits: 102, Valid: 58

  1%|          | 9103/1370754 [00:00<00:14, 91021.84it/s]

NEW score: 0.7526492459419201 previous: 0
NEW score: 0.7560110129379419 previous: 0.7526492459419201
NEW score: 0.7577654252074464 previous: 0.7560110129379419
NEW score: 0.7858547156192672 previous: 0.7577654252074464
NEW score: 0.7920407588841825 previous: 0.7858547156192672
NEW score: 0.7945795383826043 previous: 0.7920407588841825
NEW score: 0.7953243612945531 previous: 0.7945795383826043
NEW score: 0.8036854110612717 previous: 0.7953243612945531
NEW score: 0.8097947305841862 previous: 0.8036854110612717
NEW score: 0.8143041485869192 previous: 0.8097947305841862

100%|██████████| 1370754/1370754 [00:08<00:00, 162692.70it/s]

Total score: 0.8143041485869192
[Exhaustive] get topK in 8.43

,id,condition,combined,features,t_est,T0,T1,depth,algorithm,rows,total_options,validate_time,t,scan_method,scan_time,valid_options,overlap,score
0,98,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (1.836, 3.728), 'feature_4': (-3...",3,5.437,1.42,6.86,6,CT on D (Exhaustive),47,102,0.01,3.701,Exhaustive,8.43,58,0.178697,0.910652
1,97,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (1.836, 3.728), 'feature_4': (-3...",4,4.474,0.75,5.23,7,CT on D (Exhaustive),44,102,0.01,2.750,Exhaustive,8.43,58,0.182497,0.820192
2,13,feature_0 <= -1.656 AND feature_8 > 0.684 AND ...,"{'feature_0': (-4.295, -1.656), 'feature_8': (...",2,4.295,3.88,-0.41,3,CT on D (Exhaustive),39,102,0.01,1.444,Exhaustive,8.43,58,0.000000,0.894979
3,72,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (-0.41, 0.901), 'feature_1': (-0...",5,3.074,0.66,3.73,8,CT on D (Exhaustive),54,102,0.01,1.063,Exhaustive,8.43,58,0.027860,0.768763
4,76,feature_0 > -1.656 AND feature_0 > -0.41 AND f...,"{'feature_0': (0.901, 1.836)}",1,1.924,1.08,3.00,4,CT on D (Exhaustive),919,102,0.01,2.097,Exhaustive,8.43,58,0.000000,0.676936

In [4]:
debug(CTP, Greedy)

[CT on P] Offline time: 0.0
User condition: feature_6 > -0.203 Selectivity: 0.584

100%|██████████| 110/110 [00:00<00:00, 10258.21it/s]

[CT on P] Online time: 0.12, Total Splits: 110, Valid: 102
Replacing 0.6097655006081587 with 0.8580183474599247
New min score 0.7319129941531592
Replacing 0.7319129941531592 with 0.7360768178925131
New min score 0.763430298506591
Total score: 0.8410447090194395
[CT on P] get topK in 0.01

,id,condition,combined,features,t_est,T0,T1,depth,algorithm,rows,total_options,validate_time,t,scan_method,scan_time,valid_options,overlap,score
0,98,feature_0 > 0.172 AND feature_1 > -1.881 AND f...,"{'feature_0': (0.172, 1.804), 'feature_1': (1....",4,4.965,0.51,5.47,8,CT on P (Greedy),98,110,0.06,2.631,Greedy,0.0,102,0.188706,0.905647
1,108,feature_0 > 0.172 AND feature_1 > -1.881 AND f...,"{'feature_0': (1.804, 3.728), 'feature_1': (-1...",4,4.716,0.97,5.68,5,CT on P (Greedy),91,110,0.06,3.066,Greedy,0.0,102,0.198213,0.875818
2,60,feature_0 <= 0.172 AND feature_0 > -1.769 AND ...,"{'feature_0': (-0.677, 0.172), 'feature_1': (1...",4,4.102,-0.62,3.48,6,CT on P (Greedy),51,110,0.06,1.499,Greedy,0.0,102,0.221217,0.802483
3,6,feature_0 <= 0.172 AND feature_0 <= -1.769 AND...,"{'feature_0': (-4.295, -2.077), 'feature_5': (...",2,3.562,1.81,-1.76,4,CT on P (Greedy),50,110,0.06,1.577,Greedy,0.0,102,0.001732,0.857845
4,47,feature_0 <= 0.172 AND feature_0 > -1.769 AND ...,"{'feature_0': (-0.081, 0.172), 'feature_1': (-...",3,3.161,1.20,4.37,6,CT on P (Greedy),52,110,0.06,0.984,Greedy,0.0,102,0.109796,0.763430

In [5]:
debug(CTP, Exhaustive)

[CT on P] Offline time: 0.0
User condition: feature_6 > -0.203 Selectivity: 0.584

100%|██████████| 110/110 [00:00<00:00, 10899.70it/s]

[CT on P] Online time: 0.08, Total Splits: 110, Valid: 102

  0%|          | 15543/25621596 [00:00<02:44, 155420.51it/s]

NEW score: 0.698450624466091 previous: 0
NEW score: 0.711007559869763 previous: 0.698450624466091
NEW score: 0.8060007278621555 previous: 0.711007559869763
NEW score: 0.8179617519438617 previous: 0.8060007278621555
NEW score: 0.8239433862650962 previous: 0.8179617519438617
NEW score: 0.8242186628417224 previous: 0.8239433862650962
NEW score: 0.8410447090194395 previous: 0.8242186628417224

100%|██████████| 25621596/25621596 [02:35<00:00, 165195.03it/s]

Total score: 0.8410447090194395
[CT on P] get topK in 155.1

,id,condition,combined,features,t_est,T0,T1,depth,algorithm,rows,total_options,validate_time,t,scan_method,scan_time,valid_options,overlap,score
0,98,feature_0 > 0.172 AND feature_1 > -1.881 AND f...,"{'feature_0': (0.172, 1.804), 'feature_1': (1....",4,4.965,0.51,5.47,8,CT on P (Exhaustive),98,110,0.03,2.631,Exhaustive,155.1,102,0.188706,0.905647
1,108,feature_0 > 0.172 AND feature_1 > -1.881 AND f...,"{'feature_0': (1.804, 3.728), 'feature_1': (-1...",4,4.716,0.97,5.68,5,CT on P (Exhaustive),91,110,0.03,3.066,Exhaustive,155.1,102,0.198213,0.875818
2,60,feature_0 <= 0.172 AND feature_0 > -1.769 AND ...,"{'feature_0': (-0.677, 0.172), 'feature_1': (1...",4,4.102,-0.62,3.48,6,CT on P (Exhaustive),51,110,0.03,1.499,Exhaustive,155.1,102,0.221217,0.802483
3,6,feature_0 <= 0.172 AND feature_0 <= -1.769 AND...,"{'feature_0': (-4.295, -2.077), 'feature_5': (...",2,3.562,1.81,-1.76,4,CT on P (Exhaustive),50,110,0.03,1.577,Exhaustive,155.1,102,0.001732,0.857845
4,47,feature_0 <= 0.172 AND feature_0 > -1.769 AND ...,"{'feature_0': (-0.081, 0.172), 'feature_1': (-...",3,3.161,1.20,4.37,6,CT on P (Exhaustive),52,110,0.03,0.984,Exhaustive,155.1,102,0.109796,0.763430

In [10]:
debug(CFT, scanner=Greedy)

100%|██████████| 258/258 [00:00<00:00, 4800.98it/s]

[CF SingleTree] Offline time: 7.51
User condition: feature_5 <= 0.665 Selectivity: 0.7458
[CF SingleTree] Online time: 0.05, Total Splits: 258, Valid: 255
Replacing 0.49902492391007974 with 0.6170672823554466
New min score 0.5350491705613735
Replacing 0.5350491705613735 with 0.6647835440906544
New min score 0.5826008509005866
Replacing 0.5826008509005866 with 0.6934967654068778
New min score 0.6528635405866074
Replacing 0.6528635405866074 with 0.6893133258870584
New min score 0.6825013630263379
Replacing 0.6825013630263379 with 0.6870638295442055
New min score 0.7011378892507579
Replacing 0.7011378892507579 with 0.8515088013214058
New min score 0.7880307601133387
Replacing 0.7880307601133387 with 0.8182977391601718
New min score 0.7921958805164778
Replacing 0.7921958805164778 with 0.8419656736094667
New min score 0.8221788806501994
Replacing 0.8221788806501994 with 0.8389468795425512
New min score 0.8091050826158472
Replacing 0.8091050826158472 with 0.8376404494382024
New min score 0.8251404494382023
Total score: 0.8900897148819327
[Greedy] get topK in 0.0

,id,condition,combined,features,t_est,depth,algorithm,rows,total_options,validate_time,t,scan_method,scan_time,valid_options,overlap,score
0,255,feature_0 > 0.076 AND feature_0 > 1.597 AND fe...,"{'feature_0': (1.96, 3.728), 'feature_1': (-0....",4,2.767,8,CF SingleTree (Greedy),24,258,0.05,3.005,Greedy,0.0,255,0.00099,0.970564
1,226,feature_0 > 0.076 AND feature_0 <= 1.597 AND f...,"{'feature_0': (0.986, 1.597), 'feature_1': (1....",4,2.514,8,CF SingleTree (Greedy),29,258,0.05,3.124,Greedy,0.0,255,0.12500,0.865488
2,237,feature_0 > 0.076 AND feature_0 > 1.597 AND fe...,"{'feature_0': (1.597, 1.834), 'feature_1': (0....",2,2.352,5,CF SingleTree (Greedy),29,258,0.05,2.901,Greedy,0.0,255,0.00000,0.900409
3,241,feature_0 > 0.076 AND feature_0 > 1.597 AND fe...,"{'feature_0': (1.834, 1.975), 'feature_1': (-4...",2,2.287,5,CF SingleTree (Greedy),24,258,0.05,2.224,Greedy,0.0,255,0.00099,0.888848
4,217,feature_0 > 0.076 AND feature_0 <= 1.597 AND f...,"{'feature_0': (0.421, 0.986), 'feature_1': (1....",2,2.277,6,CF SingleTree (Greedy),115,258,0.05,2.646,Greedy,0.0,255,0.12500,0.825140

In [11]:
debug(CF, scanner=Greedy)

100%|██████████| 4950/4950 [00:20<00:00, 243.84it/s]

[CF] Offline time: 23.95
User condition: feature_5 <= 0.665 Selectivity: 0.7458
[CF] Online time: 0.78, Total Splits: 4950, Valid: 4392
Replacing 0.5218426995903817 with 0.5991559570309106
New min score 0.5889975286773734
Replacing 0.5889975286773734 with 0.5957231855277292
New min score 0.5563205214710483
Replacing 0.5563205214710483 with 0.7480804081040203
New min score 0.6529505890407925
Replacing 0.6529505890407925 with 0.836676523724605
New min score 0.7345465481679108
Replacing 0.7345465481679108 with 0.771221193523957
New min score 0.7603019079651026
Total score: 0.8141823499030852
[Greedy] get topK in 0.04

,id,condition,combined,features,t_est,depth,algorithm,rows,total_options,validate_time,t,scan_method,scan_time,valid_options,overlap,score
0,4948,feature_0 > -0.102 AND feature_0 > 1.596 AND f...,"{'feature_0': (1.596, 3.728), 'feature_5': (-3...",3,5.736,4,CF (Greedy),183,4950,0.78,3.428,Greedy,0.01,4392,0.204154,0.891555
1,1674,feature_0 > 0.071 AND feature_1 <= 1.192 AND f...,"{'feature_0': (1.947, 3.728), 'feature_1': (-4...",3,5.286,4,CF (Greedy),85,4950,0.78,3.006,Greedy,0.01,4392,0.339770,0.785020
2,2354,feature_0 <= 0.418 AND feature_1 > -0.072 AND ...,"{'feature_0': (-4.295, 0.418), 'feature_1': (-...",5,4.484,8,CF (Greedy),100,4950,0.78,0.612,Greedy,0.01,4392,0.200178,0.785798
3,2383,feature_0 > 0.418 AND feature_0 <= 1.672 AND f...,"{'feature_0': (0.418, 1.672), 'feature_1': (1....",2,4.381,4,CF (Greedy),111,4950,0.78,2.654,Greedy,0.01,4392,0.057570,0.848237
4,3342,feature_0 > 0.931 AND feature_1 <= 1.099 AND f...,"{'feature_0': (0.931, 1.074), 'feature_1': (-4...",3,4.039,5,CF (Greedy),113,4950,0.78,1.666,Greedy,0.01,4392,0.174577,0.760302