In [1]:
%load_ext autoreload
%autoreload 2

from trees.data import Data
data = Data()
data.generate()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,outcome,treatment,ITE,id
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,0.002523,-0.001684,-0.008669,-0.007690,0.012437,0.002649,0.012918,0.001693,0.001131,-0.005640,1.437047,0.502100,0.806172,4999.50000
std,1.022027,0.992098,1.003031,0.992401,0.998175,1.001443,1.010710,1.001298,0.995909,0.991762,3.290630,0.500021,1.158088,2886.89568
min,-4.295391,-4.465604,-3.940008,-3.631539,-3.856375,-3.726141,-4.462969,-3.601085,-3.419906,-4.157734,-12.041417,0.000000,-4.157076,0.00000
25%,-0.685254,-0.670339,-0.684620,-0.673858,-0.661041,-0.671775,-0.661183,-0.684996,-0.677070,-0.680137,-0.768118,0.000000,0.030921,2499.75000
50%,0.007853,-0.017794,-0.014492,0.005256,0.012248,0.009466,0.017331,0.001488,0.003151,0.003104,1.399103,1.000000,0.786993,4999.50000
75%,0.686816,0.666640,0.664414,0.657044,0.690269,0.676462,0.698700,0.672743,0.672574,0.674684,3.573415,1.000000,1.559871,7499.25000
max,3.727833,3.942331,3.829782,4.479084,3.594374,3.926238,3.602832,3.712795,3.605591,3.852731,14.667230,1.000000,6.516317,9999.00000

In [2]:
from trees.brute_force import BruteForce
from trees.causal_forest import CF

cf = CF(data, debug=True)
cf.fit()

bf = BruteForce(cf, oracle=True, debug=True)
bf.fit()

feature_0:100
feature_1:96
Generated 8056 options

In [3]:
data.generate_random_condition()

('feature_5 <= 0.6648712552462976', 0.7458)

In [17]:
data.set_overlap_measure('overlap_coefficient')
cf.scan()
top_cf = data.get_topK(cf, w=0.5, k=10)
top_cf

2952 total splits
Scan time: 1.09
Time to retrieve top-K 0.02

,condition,t_est,overlap,depth,rows,selectivity,selectivity_to_P_ratio,norm_cate,score,t,features,unique_between_K,true_score,algorithm,execution_time
0,feature_0 <= 0.038 AND feature_1 <= -0.611 AND...,76.166,0.841,4,44,0.0044,0.005900,1.00,0.92,0.521,4.0,0.529876,0.46,CF,1.11
1,feature_0 <= -1.272 AND feature_1 <= -1.266 AN...,5.727,1.000,4,32,0.0032,0.004291,0.08,0.54,1.702,3.0,0.529876,0.63,CF,1.11
2,feature_0 > 1.561 AND feature_1 > 1.08 AND fea...,24.580,0.750,3,36,0.0036,0.004827,0.32,0.54,3.991,3.0,0.529876,0.68,CF,1.11
3,feature_0 <= -0.937 AND feature_5 <= -0.697 AN...,5.323,1.000,4,18,0.0018,0.002414,0.07,0.53,0.923,3.0,0.529876,0.57,CF,1.11
4,feature_0 > 0.101 AND feature_0 > 1.95 AND fea...,4.856,1.000,4,53,0.0053,0.007106,0.06,0.53,3.156,3.0,0.529876,0.74,CF,1.11
5,feature_0 > -0.032 AND feature_0 > 1.667 AND f...,4.697,1.000,4,222,0.0222,0.029767,0.06,0.53,2.982,3.0,0.529876,0.73,CF,1.11
6,feature_0 > 0.101 AND feature_0 > 1.95 AND fea...,4.577,1.000,3,145,0.0145,0.019442,0.06,0.53,3.182,2.0,0.529876,0.74,CF,1.11
7,feature_0 > -0.934 AND feature_1 > 1.677 AND f...,4.353,1.000,4,60,0.0060,0.008045,0.06,0.53,2.593,4.0,0.529876,0.70,CF,1.11
8,feature_0 > 0.101 AND feature_0 > 1.95 AND fea...,4.320,1.000,4,92,0.0092,0.012336,0.06,0.53,3.197,3.0,0.529876,0.75,CF,1.11
9,feature_0 > -0.959 AND feature_1 > -0.346 AND ...,4.011,1.000,4,185,0.0185,0.024806,0.05,0.53,3.141,3.0,0.529876,0.74,CF,1.11

In [9]:
import pandas as pd

df = pd.DataFrame(bf.scores)
df = df.sort_values(by='overlap', ascending=False)
df

,condition,t_est,overlap,depth,rows,selectivity,selectivity_to_P_ratio
6994,feature_0 > 0.7 AND feature_0 < 2.2 AND featur...,1.258,0.941,4,51,0.0051,0.006838
6988,feature_0 > 0.7 AND feature_0 < 2.2 AND featur...,1.258,0.941,4,51,0.0051,0.006838
6970,feature_0 > 0.7 AND feature_0 < 2.2 AND featur...,1.258,0.941,3,51,0.0051,0.006838
6982,feature_0 > 0.7 AND feature_0 < 2.2 AND featur...,1.258,0.941,4,51,0.0051,0.006838
7233,feature_0 > 0.7 AND feature_0 < 3.7 AND featur...,1.426,0.930,3,57,0.0057,0.007643
...,...,...,...,...,...,...,...
7753,feature_0 > 1.7 AND feature_0 < 2.2 AND featur...,2.779,0.625,4,72,0.0072,0.009654
7816,feature_0 > 1.7 AND feature_0 < 2.7 AND featur...,2.850,0.621,4,87,0.0087,0.011665
7948,feature_0 > 1.7 AND feature_0 < 3.7 AND featur...,2.959,0.619,4,97,0.0097,0.013006
1208,feature_0 > 1.7 AND feature_1 > 0.03 AND featu...,2.959,0.619,3,97,0.0097,0.013006
7882,feature_0 > 1.7 AND feature_0 < 3.2 AND featur...,2.917,0.617,4,94,0.0094,0.012604

In [5]:
bf.scan()
top_bf = data.get_topK(alg=bf, w=0.5, k=10)
top_bf

Scan time: 2.42
Time to retrieve top-K 0.12

,condition,t_est,overlap,depth,rows,selectivity,selectivity_to_P_ratio,norm_cate,score,t,features,unique_between_K,true_score,algorithm,execution_time
0,feature_0 > 2.2 AND feature_1 > 0.53 AND featu...,4.051,0.830,3,53,0.0053,0.007106,1.00,0.92,4.051,2.0,0.297393,0.73,Brute Force (Oracle),2.54
1,feature_0 > 1.7 AND feature_0 < 3.7 AND featur...,3.979,0.767,3,86,0.0086,0.011531,0.98,0.87,3.979,2.0,0.297393,0.69,Brute Force (Oracle),2.54
2,feature_0 > 2.2 AND feature_1 > 0.03,3.866,0.756,2,78,0.0078,0.010459,0.95,0.86,3.866,2.0,0.297393,0.67,Brute Force (Oracle),2.54
3,feature_0 > 1.7 AND feature_0 < 2.2 AND featur...,3.786,0.774,3,53,0.0053,0.007106,0.93,0.85,3.786,2.0,0.297393,0.68,Brute Force (Oracle),2.54
4,feature_0 > 1.7 AND feature_1 > 0.53,3.699,0.778,2,144,0.0144,0.019308,0.91,0.85,3.699,2.0,0.297393,0.67,Brute Force (Oracle),2.54
5,feature_0 > 2.2 AND feature_1 > -0.47,3.704,0.770,2,100,0.0100,0.013408,0.91,0.84,3.704,2.0,0.297393,0.67,Brute Force (Oracle),2.54
6,feature_0 > 1.7 AND feature_0 < 2.7 AND featur...,3.762,0.754,4,65,0.0065,0.008715,0.93,0.84,3.762,2.0,0.297393,0.67,Brute Force (Oracle),2.54
7,feature_0 > 1.2 AND feature_1 > 1.53 AND featu...,3.795,0.740,3,100,0.0100,0.013408,0.94,0.84,3.795,2.0,0.297393,0.66,Brute Force (Oracle),2.54
8,feature_0 > 1.7 AND feature_1 > 0.53 AND featu...,3.470,0.798,3,104,0.0104,0.013945,0.86,0.83,3.470,2.0,0.297393,0.67,Brute Force (Oracle),2.54
9,feature_0 > 2.2 AND feature_0 < 3.2 AND featur...,3.633,0.754,4,61,0.0061,0.008179,0.90,0.83,3.633,2.0,0.297393,0.66,Brute Force (Oracle),2.54

In [16]:
df2 = data.execute("feature_0 <= -0.032 AND feature_1 > 0.888 AND feature_9 > 1.459 AND feature_5 <= -0.037")
bf.D.overlap_coefficient(bf.D.q_df, df2)

1.0

In [8]:
bf.generate_combinations_for_feature('feature_0')

['feature_0 > -4.3',
 'feature_0 > -3.8',
 'feature_0 > -3.3',
 'feature_0 > -2.8',
 'feature_0 > -2.3',
 'feature_0 < -2.3',
 'feature_0 > -1.8',
 'feature_0 < -1.8',
 'feature_0 > -1.3',
 'feature_0 < -1.3',
 'feature_0 > -0.8',
 'feature_0 < -0.8',
 'feature_0 > -0.3',
 'feature_0 < -0.3',
 'feature_0 > 0.2',
 'feature_0 < 0.2',
 'feature_0 > 0.7',
 'feature_0 < 0.7',
 'feature_0 > 1.2',
 'feature_0 < 1.2',
 'feature_0 > 1.7',
 'feature_0 < 1.7',
 'feature_0 > 2.2',
 'feature_0 < 2.2',
 'feature_0 < 2.7',
 'feature_0 < 3.2',
 'feature_0 < 3.7',
 'feature_0 > -4.3 and feature_0 < -2.3',
 'feature_0 > -4.3 and feature_0 < -1.8',
 'feature_0 > -4.3 and feature_0 < -1.3',
 'feature_0 > -4.3 and feature_0 < -0.8',
 'feature_0 > -4.3 and feature_0 < -0.3',
 'feature_0 > -4.3 and feature_0 < 0.2',
 'feature_0 > -4.3 and feature_0 < 0.7',
 'feature_0 > -4.3 and feature_0 < 1.2',
 'feature_0 > -4.3 and feature_0 < 1.7',
 'feature_0 > -4.3 and feature_0 < 2.2',
 'feature_0 > -4.3 and feature_0 < 2.7',
 'feature_0 > -4.3 and feature_0 < 3.2',
 'feature_0 > -4.3 and feature_0 < 3.7',
 'feature_0 > -3.8 and feature_0 < -2.3',
 'feature_0 > -3.8 and feature_0 < -1.8',
 'feature_0 > -3.8 and feature_0 < -1.3',
 'feature_0 > -3.8 and feature_0 < -0.8',
 'feature_0 > -3.8 and feature_0 < -0.3',
 'feature_0 > -3.8 and feature_0 < 0.2',
 'feature_0 > -3.8 and feature_0 < 0.7',
 'feature_0 > -3.8 and feature_0 < 1.2',
 'feature_0 > -3.8 and feature_0 < 1.7',
 'feature_0 > -3.8 and feature_0 < 2.2',
 'feature_0 > -3.8 and feature_0 < 2.7',
 'feature_0 > -3.8 and feature_0 < 3.2',
 'feature_0 > -3.8 and feature_0 < 3.7',
 'feature_0 > -3.3 and feature_0 < -2.3',
 'feature_0 > -3.3 and feature_0 < -1.8',
 'feature_0 > -3.3 and feature_0 < -1.3',
 'feature_0 > -3.3 and feature_0 < -0.8',
 'feature_0 > -3.3 and feature_0 < -0.3',
 'feature_0 > -3.3 and feature_0 < 0.2',
 'feature_0 > -3.3 and feature_0 < 0.7',
 'feature_0 > -3.3 and feature_0 < 1.2',
 'feature_0 > -3.3 and feature_0 < 1.7',
 'feature_0 > -3.3 and feature_0 < 2.2',
 'feature_0 > -3.3 and feature_0 < 2.7',
 'feature_0 > -3.3 and feature_0 < 3.2',
 'feature_0 > -3.3 and feature_0 < 3.7',
 'feature_0 > -2.8 and feature_0 < -2.3',
 'feature_0 > -2.8 and feature_0 < -1.8',
 'feature_0 > -2.8 and feature_0 < -1.3',
 'feature_0 > -2.8 and feature_0 < -0.8',
 'feature_0 > -2.8 and feature_0 < -0.3',
 'feature_0 > -2.8 and feature_0 < 0.2',
 'feature_0 > -2.8 and feature_0 < 0.7',
 'feature_0 > -2.8 and feature_0 < 1.2',
 'feature_0 > -2.8 and feature_0 < 1.7',
 'feature_0 > -2.8 and feature_0 < 2.2',
 'feature_0 > -2.8 and feature_0 < 2.7',
 'feature_0 > -2.8 and feature_0 < 3.2',
 'feature_0 > -2.8 and feature_0 < 3.7',
 'feature_0 > -2.3 and feature_0 < -1.8',
 'feature_0 > -2.3 and feature_0 < -1.3',
 'feature_0 > -2.3 and feature_0 < -0.8',
 'feature_0 > -2.3 and feature_0 < -0.3',
 'feature_0 > -2.3 and feature_0 < 0.2',
 'feature_0 > -2.3 and feature_0 < 0.7',
 'feature_0 > -2.3 and feature_0 < 1.2',
 'feature_0 > -2.3 and feature_0 < 1.7',
 'feature_0 > -2.3 and feature_0 < 2.2',
 'feature_0 > -2.3 and feature_0 < 2.7',
 'feature_0 > -2.3 and feature_0 < 3.2',
 'feature_0 > -2.3 and feature_0 < 3.7',
 'feature_0 > -1.8 and feature_0 < -1.3',
 'feature_0 > -1.8 and feature_0 < -0.8',
 'feature_0 > -1.8 and feature_0 < -0.3',
 'feature_0 > -1.8 and feature_0 < 0.2',
 'feature_0 > -1.8 and feature_0 < 0.7',
 'feature_0 > -1.8 and feature_0 < 1.2',
 'feature_0 > -1.8 and feature_0 < 1.7',
 'feature_0 > -1.8 and feature_0 < 2.2',
 'feature_0 > -1.8 and feature_0 < 2.7',
 'feature_0 > -1.8 and feature_0 < 3.2',
 'feature_0 > -1.8 and feature_0 < 3.7',
 'feature_0 > -1.3 and feature_0 < -0.8',
 'feature_0 > -1.3 and feature_0 < -0.3',
 'feature_0 > -1.3 and feature_0 < 0.2',
 'feature_0 > -1.3 and feature_0 < 0.7',
 'feature_0 > -1.3 and feature_0 < 1.2',
 'feature_0 > -1.3 and feature_0 < 1.7',
 'feature_0 > -1.3 and feature_0 < 2.2',
 'feature_0 > -1.3 and feature_0 < 2.7',
 'feature_0 > -1.3 and feature_0 < 3.2',
 'feature_0 > -1.3 and feature_0 < 3.7',
 'feature_0 > -0.8 and feature_0 < -0.3',
 'feature_0 > -0.8 and feature_0 < 0.2',
 'feature_0 > -0.8 and feature_0 < 0.7',
 'feature_0 > -0.8 and feature_0 < 1.2',
 'feature_0 > -0.8 and feature_0 < 1.7',
 'feature_0 > -0.8 and feature_0 < 2.2',
 'feature_0 > -0.8 and feature_0 < 2.7',
 'feature_0 > -0.8 and feature_0 < 3.2',
 'feature_0 > -0.8 and feature_0 < 3.7',
 'feature_0 > -0.3 and feature_0 < 0.2',
 'feature_0 > -0.3 and feature_0 < 0.7',
 'feature_0 > -0.3 and feature_0 < 1.2',
 'feature_0 > -0.3 and feature_0 < 1.7',
 'feature_0 > -0.3 and feature_0 < 2.2',
 'feature_0 > -0.3 and feature_0 < 2.7',
 'feature_0 > -0.3 and feature_0 < 3.2',
 'feature_0 > -0.3 and feature_0 < 3.7',
 'feature_0 > 0.2 and feature_0 < 0.7',
 'feature_0 > 0.2 and feature_0 < 1.2',
 'feature_0 > 0.2 and feature_0 < 1.7',
 'feature_0 > 0.2 and feature_0 < 2.2',
 'feature_0 > 0.2 and feature_0 < 2.7',
 'feature_0 > 0.2 and feature_0 < 3.2',
 'feature_0 > 0.2 and feature_0 < 3.7',
 'feature_0 > 0.7 and feature_0 < 1.2',
 'feature_0 > 0.7 and feature_0 < 1.7',
 'feature_0 > 0.7 and feature_0 < 2.2',
 'feature_0 > 0.7 and feature_0 < 2.7',
 'feature_0 > 0.7 and feature_0 < 3.2',
 'feature_0 > 0.7 and feature_0 < 3.7',
 'feature_0 > 1.2 and feature_0 < 1.7',
 'feature_0 > 1.2 and feature_0 < 2.2',
 'feature_0 > 1.2 and feature_0 < 2.7',
 'feature_0 > 1.2 and feature_0 < 3.2',
 'feature_0 > 1.2 and feature_0 < 3.7',
 'feature_0 > 1.7 and feature_0 < 2.2',
 'feature_0 > 1.7 and feature_0 < 2.7',
 'feature_0 > 1.7 and feature_0 < 3.2',
 'feature_0 > 1.7 and feature_0 < 3.7',
 'feature_0 > 2.2 and feature_0 < 2.7',
 'feature_0 > 2.2 and feature_0 < 3.2',
 'feature_0 > 2.2 and feature_0 < 3.7']

In [11]:
combs = bf.generate_combinations_multiple_features(['feature_0', 'feature_1'])
combs

feature_0:100
feature_1:96

['feature_0 < -2.3',
 'feature_0 < -1.8',
 'feature_0 < -1.3',
 'feature_0 > -0.8',
 'feature_0 < -0.8',
 'feature_0 > -0.3',
 'feature_0 < -0.3',
 'feature_0 > 0.2',
 'feature_0 < 0.2',
 'feature_0 > 0.7',
 'feature_0 < 0.7',
 'feature_0 > 1.2',
 'feature_0 > 1.7',
 'feature_0 > 2.2',
 'feature_0 > -4.3 AND feature_0 < -2.3',
 'feature_0 > -4.3 AND feature_0 < -1.8',
 'feature_0 > -4.3 AND feature_0 < -1.3',
 'feature_0 > -4.3 AND feature_0 < -0.8',
 'feature_0 > -4.3 AND feature_0 < -0.3',
 'feature_0 > -4.3 AND feature_0 < 0.2',
 'feature_0 > -4.3 AND feature_0 < 0.7',
 'feature_0 > -3.8 AND feature_0 < -2.3',
 'feature_0 > -3.8 AND feature_0 < -1.8',
 'feature_0 > -3.8 AND feature_0 < -1.3',
 'feature_0 > -3.8 AND feature_0 < -0.8',
 'feature_0 > -3.8 AND feature_0 < -0.3',
 'feature_0 > -3.8 AND feature_0 < 0.2',
 'feature_0 > -3.8 AND feature_0 < 0.7',
 'feature_0 > -3.3 AND feature_0 < -2.3',
 'feature_0 > -3.3 AND feature_0 < -1.8',
 'feature_0 > -3.3 AND feature_0 < -1.3',
 'feature_0 > -3.3 AND feature_0 < -0.8',
 'feature_0 > -3.3 AND feature_0 < -0.3',
 'feature_0 > -3.3 AND feature_0 < 0.2',
 'feature_0 > -3.3 AND feature_0 < 0.7',
 'feature_0 > -2.8 AND feature_0 < -2.3',
 'feature_0 > -2.8 AND feature_0 < -1.8',
 'feature_0 > -2.8 AND feature_0 < -1.3',
 'feature_0 > -2.8 AND feature_0 < -0.8',
 'feature_0 > -2.8 AND feature_0 < -0.3',
 'feature_0 > -2.8 AND feature_0 < 0.2',
 'feature_0 > -2.8 AND feature_0 < 0.7',
 'feature_0 > -2.3 AND feature_0 < -1.8',
 'feature_0 > -2.3 AND feature_0 < -1.3',
 'feature_0 > -2.3 AND feature_0 < -0.8',
 'feature_0 > -2.3 AND feature_0 < -0.3',
 'feature_0 > -2.3 AND feature_0 < 0.2',
 'feature_0 > -2.3 AND feature_0 < 0.7',
 'feature_0 > -1.8 AND feature_0 < -1.3',
 'feature_0 > -1.8 AND feature_0 < -0.8',
 'feature_0 > -1.8 AND feature_0 < -0.3',
 'feature_0 > -1.8 AND feature_0 < 0.2',
 'feature_0 > -1.8 AND feature_0 < 0.7',
 'feature_0 > -1.3 AND feature_0 < -0.8',
 'feature_0 > -1.3 AND feature_0 < -0.3',
 'feature_0 > -1.3 AND feature_0 < 0.2',
 'feature_0 > -1.3 AND feature_0 < 0.7',
 'feature_0 > -1.3 AND feature_0 < 1.2',
 'feature_0 > -0.8 AND feature_0 < -0.3',
 'feature_0 > -0.8 AND feature_0 < 0.2',
 'feature_0 > -0.8 AND feature_0 < 0.7',
 'feature_0 > -0.8 AND feature_0 < 1.2',
 'feature_0 > -0.8 AND feature_0 < 1.7',
 'feature_0 > -0.8 AND feature_0 < 2.2',
 'feature_0 > -0.8 AND feature_0 < 2.7',
 'feature_0 > -0.8 AND feature_0 < 3.2',
 'feature_0 > -0.8 AND feature_0 < 3.7',
 'feature_0 > -0.3 AND feature_0 < 0.2',
 'feature_0 > -0.3 AND feature_0 < 0.7',
 'feature_0 > -0.3 AND feature_0 < 1.2',
 'feature_0 > -0.3 AND feature_0 < 1.7',
 'feature_0 > -0.3 AND feature_0 < 2.2',
 'feature_0 > -0.3 AND feature_0 < 2.7',
 'feature_0 > -0.3 AND feature_0 < 3.2',
 'feature_0 > -0.3 AND feature_0 < 3.7',
 'feature_0 > 0.2 AND feature_0 < 0.7',
 'feature_0 > 0.2 AND feature_0 < 1.2',
 'feature_0 > 0.2 AND feature_0 < 1.7',
 'feature_0 > 0.2 AND feature_0 < 2.2',
 'feature_0 > 0.2 AND feature_0 < 2.7',
 'feature_0 > 0.2 AND feature_0 < 3.2',
 'feature_0 > 0.2 AND feature_0 < 3.7',
 'feature_0 > 0.7 AND feature_0 < 1.2',
 'feature_0 > 0.7 AND feature_0 < 1.7',
 'feature_0 > 0.7 AND feature_0 < 2.2',
 'feature_0 > 0.7 AND feature_0 < 2.7',
 'feature_0 > 0.7 AND feature_0 < 3.2',
 'feature_0 > 0.7 AND feature_0 < 3.7',
 'feature_0 > 1.2 AND feature_0 < 1.7',
 'feature_0 > 1.2 AND feature_0 < 2.2',
 'feature_0 > 1.2 AND feature_0 < 2.7',
 'feature_0 > 1.2 AND feature_0 < 3.2',
 'feature_0 > 1.2 AND feature_0 < 3.7',
 'feature_0 > 1.7 AND feature_0 < 2.2',
 'feature_0 > 1.7 AND feature_0 < 2.7',
 'feature_0 > 1.7 AND feature_0 < 3.2',
 'feature_0 > 1.7 AND feature_0 < 3.7',
 'feature_0 > 2.2 AND feature_0 < 2.7',
 'feature_0 > 2.2 AND feature_0 < 3.2',
 'feature_0 > 2.2 AND feature_0 < 3.7',
 'feature_1 < -2.47',
 'feature_1 < -1.97',
 'feature_1 < -1.47',
 'feature_1 < -0.97',
 'feature_1 > -0.47',
 'feature_1 < -0.47',
 'feature_1 > 0.03',
 'feature_1 < 0.03',
 'feature_1 > 0.53',
 'feature_1 < 0.53',
 'feature_1 > 1.03',
 'feature_1 > 1.53',
 'feature_1 > 2.03',
 'feature_1 > 2.53',
 'feature_1 > -4.47 AND feature_1 < -2.47',
 'feature_1 > -4.47 AND feature_1 < -1.97',
 'feature_1 > -4.47 AND feature_1 < -1.47',
 'feature_1 > -4.47 AND feature_1 < -0.97',
 'feature_1 > -4.47 AND feature_1 < -0.47',
 'feature_1 > -4.47 AND feature_1 < 0.03',
 'feature_1 > -4.47 AND feature_1 < 0.53',
 'feature_1 > -3.97 AND feature_1 < -2.47',
 'feature_1 > -3.97 AND feature_1 < -1.97',
 'feature_1 > -3.97 AND feature_1 < -1.47',
 'feature_1 > -3.97 AND feature_1 < -0.97',
 'feature_1 > -3.97 AND feature_1 < -0.47',
 'feature_1 > -3.97 AND feature_1 < 0.03',
 'feature_1 > -3.97 AND feature_1 < 0.53',
 'feature_1 > -3.47 AND feature_1 < -2.47',
 'feature_1 > -3.47 AND feature_1 < -1.97',
 'feature_1 > -3.47 AND feature_1 < -1.47',
 'feature_1 > -3.47 AND feature_1 < -0.97',
 'feature_1 > -3.47 AND feature_1 < -0.47',
 'feature_1 > -3.47 AND feature_1 < 0.03',
 'feature_1 > -3.47 AND feature_1 < 0.53',
 'feature_1 > -2.97 AND feature_1 < -1.97',
 'feature_1 > -2.97 AND feature_1 < -1.47',
 'feature_1 > -2.97 AND feature_1 < -0.97',
 'feature_1 > -2.97 AND feature_1 < -0.47',
 'feature_1 > -2.97 AND feature_1 < 0.03',
 'feature_1 > -2.97 AND feature_1 < 0.53',
 'feature_1 > -2.47 AND feature_1 < -1.97',
 'feature_1 > -2.47 AND feature_1 < -1.47',
 'feature_1 > -2.47 AND feature_1 < -0.97',
 'feature_1 > -2.47 AND feature_1 < -0.47',
 'feature_1 > -2.47 AND feature_1 < 0.03',
 'feature_1 > -2.47 AND feature_1 < 0.53',
 'feature_1 > -1.97 AND feature_1 < -1.47',
 'feature_1 > -1.97 AND feature_1 < -0.97',
 'feature_1 > -1.97 AND feature_1 < -0.47',
 'feature_1 > -1.97 AND feature_1 < 0.03',
 'feature_1 > -1.97 AND feature_1 < 0.53',
 'feature_1 > -1.47 AND feature_1 < -0.97',
 'feature_1 > -1.47 AND feature_1 < -0.47',
 'feature_1 > -1.47 AND feature_1 < 0.03',
 'feature_1 > -1.47 AND feature_1 < 0.53',
 'feature_1 > -1.47 AND feature_1 < 1.03',
 'feature_1 > -0.97 AND feature_1 < -0.47',
 'feature_1 > -0.97 AND feature_1 < 0.03',
 'feature_1 > -0.97 AND feature_1 < 0.53',
 'feature_1 > -0.97 AND feature_1 < 1.03',
 'feature_1 > -0.97 AND feature_1 < 1.53',
 'feature_1 > -0.47 AND feature_1 < 0.03',
 'feature_1 > -0.47 AND feature_1 < 0.53',
 'feature_1 > -0.47 AND feature_1 < 1.03',
 'feature_1 > -0.47 AND feature_1 < 1.53',
 'feature_1 > -0.47 AND feature_1 < 2.03',
 'feature_1 > -0.47 AND feature_1 < 2.53',
 'feature_1 > -0.47 AND feature_1 < 3.03',
 'feature_1 > -0.47 AND feature_1 < 3.53',
 'feature_1 > 0.03 AND feature_1 < 0.53',
 'feature_1 > 0.03 AND feature_1 < 1.03',
 'feature_1 > 0.03 AND feature_1 < 1.53',
 'feature_1 > 0.03 AND feature_1 < 2.03',
 'feature_1 > 0.03 AND feature_1 < 2.53',
 'feature_1 > 0.03 AND feature_1 < 3.03',
 'feature_1 > 0.03 AND feature_1 < 3.53',
 'feature_1 > 0.53 AND feature_1 < 1.03',
 'feature_1 > 0.53 AND feature_1 < 1.53',
 'feature_1 > 0.53 AND feature_1 < 2.03',
 'feature_1 > 0.53 AND feature_1 < 2.53',
 'feature_1 > 0.53 AND feature_1 < 3.03',
 'feature_1 > 0.53 AND feature_1 < 3.53',
 'feature_1 > 1.03 AND feature_1 < 1.53',
 'feature_1 > 1.03 AND feature_1 < 2.03',
 'feature_1 > 1.03 AND feature_1 < 2.53',
 'feature_1 > 1.03 AND feature_1 < 3.03',
 'feature_1 > 1.03 AND feature_1 < 3.53',
 'feature_1 > 1.53 AND feature_1 < 2.03',
 'feature_1 > 1.53 AND feature_1 < 2.53',
 'feature_1 > 1.53 AND feature_1 < 3.03',
 'feature_1 > 1.53 AND feature_1 < 3.53',
 'feature_1 > 2.03 AND feature_1 < 2.53',
 'feature_1 > 2.03 AND feature_1 < 3.03',
 'feature_1 > 2.03 AND feature_1 < 3.53',
 'feature_1 > 2.53 AND feature_1 < 3.53',
 'feature_0 < -2.3 AND feature_1 > -0.47',
 'feature_0 < -2.3 AND feature_1 > 0.03',
 'feature_0 < -2.3 AND feature_1 < 0.03',
 'feature_0 < -2.3 AND feature_1 < 0.53',
 'feature_0 < -2.3 AND feature_1 > -4.47 AND feature_1 < 0.03',
 'feature_0 < -2.3 AND feature_1 > -4.47 AND feature_1 < 0.53',
 'feature_0 < -2.3 AND feature_1 > -3.97 AND feature_1 < 0.03',
 'feature_0 < -2.3 AND feature_1 > -3.97 AND feature_1 < 0.53',
 'feature_0 < -2.3 AND feature_1 > -3.47 AND feature_1 < 0.03',
 'feature_0 < -2.3 AND feature_1 > -3.47 AND feature_1 < 0.53',
 'feature_0 < -2.3 AND feature_1 > -2.97 AND feature_1 < 0.03',
 'feature_0 < -2.3 AND feature_1 > -2.97 AND feature_1 < 0.53',
 'feature_0 < -2.3 AND feature_1 > -2.47 AND feature_1 < 0.03',
 'feature_0 < -2.3 AND feature_1 > -2.47 AND feature_1 < 0.53',
 'feature_0 < -2.3 AND feature_1 > -1.97 AND feature_1 < 0.03',
 'feature_0 < -2.3 AND feature_1 > -1.97 AND feature_1 < 0.53',
 'feature_0 < -2.3 AND feature_1 > -1.47 AND feature_1 < 0.03',
 'feature_0 < -2.3 AND feature_1 > -1.47 AND feature_1 < 0.53',
 'feature_0 < -2.3 AND feature_1 > -1.47 AND feature_1 < 1.03',
 'feature_0 < -2.3 AND feature_1 > -0.97 AND feature_1 < 0.53',
 'feature_0 < -2.3 AND feature_1 > -0.97 AND feature_1 < 1.03',
 'feature_0 < -2.3 AND feature_1 > -0.97 AND feature_1 < 1.53',
 'feature_0 < -2.3 AND feature_1 > -0.47 AND feature_1 < 0.53',
 'feature_0 < -2.3 AND feature_1 > -0.47 AND feature_1 < 1.03',
 'feature_0 < -2.3 AND feature_1 > -0.47 AND feature_1 < 1.53',
 'feature_0 < -2.3 AND feature_1 > -0.47 AND feature_1 < 2.03',
 'feature_0 < -2.3 AND feature_1 > -0.47 AND feature_1 < 2.53',
 'feature_0 < -2.3 AND feature_1 > -0.47 AND feature_1 < 3.03',
 'feature_0 < -2.3 AND feature_1 > -0.47 AND feature_1 < 3.53',
 'feature_0 < -2.3 AND feature_1 > 0.03 AND feature_1 < 1.53',
 'feature_0 < -2.3 AND feature_1 > 0.03 AND feature_1 < 2.03',
 'feature_0 < -2.3 AND feature_1 > 0.03 AND feature_1 < 2.53',
 'feature_0 < -2.3 AND feature_1 > 0.03 AND feature_1 < 3.03',
 'feature_0 < -2.3 AND feature_1 > 0.03 AND feature_1 < 3.53',
 'feature_0 < -1.8 AND feature_1 < -0.97',
 'feature_0 < -1.8 AND feature_1 > -0.47',
 'feature_0 < -1.8 AND feature_1 < -0.47',
 'feature_0 < -1.8 AND feature_1 > 0.03',
 'feature_0 < -1.8 AND feature_1 < 0.03',
 'feature_0 < -1.8 AND feature_1 > 0.53',
 'feature_0 < -1.8 AND feature_1 < 0.53',
 'feature_0 < -1.8 AND feature_1 > 1.03',
 'feature_0 < -1.8 AND feature_1 > -4.47 AND feature_1 < -0.97',
 'feature_0 < -1.8 AND feature_1 > -4.47 AND feature_1 < -0.47',
 'feature_0 < -1.8 AND feature_1 > -4.47 AND feature_1 < 0.03',
 'feature_0 < -1.8 AND feature_1 > -4.47 AND feature_1 < 0.53',
 'feature_0 < -1.8 AND feature_1 > -3.97 AND feature_1 < -0.97',
 'feature_0 < -1.8 AND feature_1 > -3.97 AND feature_1 < -0.47',
 'feature_0 < -1.8 AND feature_1 > -3.97 AND feature_1 < 0.03',
 'feature_0 < -1.8 AND feature_1 > -3.97 AND feature_1 < 0.53',
 'feature_0 < -1.8 AND feature_1 > -3.47 AND feature_1 < -0.97',
 'feature_0 < -1.8 AND feature_1 > -3.47 AND feature_1 < -0.47',
 'feature_0 < -1.8 AND feature_1 > -3.47 AND feature_1 < 0.03',
 'feature_0 < -1.8 AND feature_1 > -3.47 AND feature_1 < 0.53',
 'feature_0 < -1.8 AND feature_1 > -2.97 AND feature_1 < -0.97',
 'feature_0 < -1.8 AND feature_1 > -2.97 AND feature_1 < -0.47',
 'feature_0 < -1.8 AND feature_1 > -2.97 AND feature_1 < 0.03',
 'feature_0 < -1.8 AND feature_1 > -2.97 AND feature_1 < 0.53',
 'feature_0 < -1.8 AND feature_1 > -2.47 AND feature_1 < -0.97',
 'feature_0 < -1.8 AND feature_1 > -2.47 AND feature_1 < -0.47',
 'feature_0 < -1.8 AND feature_1 > -2.47 AND feature_1 < 0.03',
 'feature_0 < -1.8 AND feature_1 > -2.47 AND feature_1 < 0.53',
 'feature_0 < -1.8 AND feature_1 > -1.97 AND feature_1 < -0.97',
 'feature_0 < -1.8 AND feature_1 > -1.97 AND feature_1 < -0.47',
 'feature_0 < -1.8 AND feature_1 > -1.97 AND feature_1 < 0.03',
 'feature_0 < -1.8 AND feature_1 > -1.97 AND feature_1 < 0.53',
 'feature_0 < -1.8 AND feature_1 > -1.47 AND feature_1 < -0.47',
 'feature_0 < -1.8 AND feature_1 > -1.47 AND feature_1 < 0.03',
 'feature_0 < -1.8 AND feature_1 > -1.47 AND feature_1 < 0.53',
 'feature_0 < -1.8 AND feature_1 > -1.47 AND feature_1 < 1.03',
 'feature_0 < -1.8 AND feature_1 > -0.97 AND feature_1 < -0.47',
 'feature_0 < -1.8 AND feature_1 > -0.97 AND feature_1 < 0.03',
 'feature_0 < -1.8 AND feature_1 > -0.97 AND feature_1 < 0.53',
 'feature_0 < -1.8 AND feature_1 > -0.97 AND feature_1 < 1.03',
 'feature_0 < -1.8 AND feature_1 > -0.97 AND feature_1 < 1.53',
 'feature_0 < -1.8 AND feature_1 > -0.47 AND feature_1 < 0.03',
 'feature_0 < -1.8 AND feature_1 > -0.47 AND feature_1 < 0.53',
 'feature_0 < -1.8 AND feature_1 > -0.47 AND feature_1 < 1.03',
 'feature_0 < -1.8 AND feature_1 > -0.47 AND feature_1 < 1.53',
 'feature_0 < -1.8 AND feature_1 > -0.47 AND feature_1 < 2.03',
 'feature_0 < -1.8 AND feature_1 > -0.47 AND feature_1 < 2.53',
 'feature_0 < -1.8 AND feature_1 > -0.47 AND feature_1 < 3.03',
 'feature_0 < -1.8 AND feature_1 > -0.47 AND feature_1 < 3.53',
 'feature_0 < -1.8 AND feature_1 > 0.03 AND feature_1 < 0.53',
 'feature_0 < -1.8 AND feature_1 > 0.03 AND feature_1 < 1.03',
 'feature_0 < -1.8 AND feature_1 > 0.03 AND feature_1 < 1.53',
 'feature_0 < -1.8 AND feature_1 > 0.03 AND feature_1 < 2.03',
 'feature_0 < -1.8 AND feature_1 > 0.03 AND feature_1 < 2.53',
 'feature_0 < -1.8 AND feature_1 > 0.03 AND feature_1 < 3.03',
 'feature_0 < -1.8 AND feature_1 > 0.03 AND feature_1 < 3.53',
 'feature_0 < -1.8 AND feature_1 > 0.53 AND feature_1 < 1.03',
 'feature_0 < -1.8 AND feature_1 > 0.53 AND feature_1 < 1.53',
 'feature_0 < -1.8 AND feature_1 > 0.53 AND feature_1 < 2.03',
 'feature_0 < -1.8 AND feature_1 > 0.53 AND feature_1 < 2.53',
 'feature_0 < -1.8 AND feature_1 > 0.53 AND feature_1 < 3.03',
 'feature_0 < -1.8 AND feature_1 > 0.53 AND feature_1 < 3.53',
 'feature_0 < -1.8 AND feature_1 > 1.03 AND feature_1 < 2.53',
 'feature_0 < -1.8 AND feature_1 > 1.03 AND feature_1 < 3.03',
 'feature_0 < -1.8 AND feature_1 > 1.03 AND feature_1 < 3.53',
 'feature_0 < -1.3 AND feature_1 < -1.47',
 'feature_0 < -1.3 AND feature_1 < -0.97',
 'feature_0 < -1.3 AND feature_1 > -0.47',
 'feature_0 < -1.3 AND feature_1 < -0.47',
 'feature_0 < -1.3 AND feature_1 > 0.03',
 'feature_0 < -1.3 AND feature_1 < 0.03',
 'feature_0 < -1.3 AND feature_1 > 0.53',
 'feature_0 < -1.3 AND feature_1 < 0.53',
 'feature_0 < -1.3 AND feature_1 > 1.03',
 'feature_0 < -1.3 AND feature_1 > -4.47 AND feature_1 < -1.47',
 'feature_0 < -1.3 AND feature_1 > -4.47 AND feature_1 < -0.97',
 'feature_0 < -1.3 AND feature_1 > -4.47 AND feature_1 < -0.47',
 'feature_0 < -1.3 AND feature_1 > -4.47 AND feature_1 < 0.03',
 'feature_0 < -1.3 AND feature_1 > -4.47 AND feature_1 < 0.53',
 'feature_0 < -1.3 AND feature_1 > -3.97 AND feature_1 < -1.47',
 'feature_0 < -1.3 AND feature_1 > -3.97 AND feature_1 < -0.97',
 'feature_0 < -1.3 AND feature_1 > -3.97 AND feature_1 < -0.47',
 'feature_0 < -1.3 AND feature_1 > -3.97 AND feature_1 < 0.03',
 'feature_0 < -1.3 AND feature_1 > -3.97 AND feature_1 < 0.53',
 'feature_0 < -1.3 AND feature_1 > -3.47 AND feature_1 < -1.47',
 'feature_0 < -1.3 AND feature_1 > -3.47 AND feature_1 < -0.97',
 'feature_0 < -1.3 AND feature_1 > -3.47 AND feature_1 < -0.47',
 'feature_0 < -1.3 AND feature_1 > -3.47 AND feature_1 < 0.03',
 'feature_0 < -1.3 AND feature_1 > -3.47 AND feature_1 < 0.53',
 'feature_0 < -1.3 AND feature_1 > -2.97 AND feature_1 < -1.47',
 'feature_0 < -1.3 AND feature_1 > -2.97 AND feature_1 < -0.97',
 'feature_0 < -1.3 AND feature_1 > -2.97 AND feature_1 < -0.47',
 'feature_0 < -1.3 AND feature_1 > -2.97 AND feature_1 < 0.03',
 'feature_0 < -1.3 AND feature_1 > -2.97 AND feature_1 < 0.53',
 'feature_0 < -1.3 AND feature_1 > -2.47 AND feature_1 < -1.47',
 'feature_0 < -1.3 AND feature_1 > -2.47 AND feature_1 < -0.97',
 'feature_0 < -1.3 AND feature_1 > -2.47 AND feature_1 < -0.47',
 'feature_0 < -1.3 AND feature_1 > -2.47 AND feature_1 < 0.03',
 'feature_0 < -1.3 AND feature_1 > -2.47 AND feature_1 < 0.53',
 'feature_0 < -1.3 AND feature_1 > -1.97 AND feature_1 < -0.97',
 'feature_0 < -1.3 AND feature_1 > -1.97 AND feature_1 < -0.47',
 'feature_0 < -1.3 AND feature_1 > -1.97 AND feature_1 < 0.03',
 'feature_0 < -1.3 AND feature_1 > -1.97 AND feature_1 < 0.53',
 'feature_0 < -1.3 AND feature_1 > -1.47 AND feature_1 < -0.97',
 'feature_0 < -1.3 AND feature_1 > -1.47 AND feature_1 < -0.47',
 'feature_0 < -1.3 AND feature_1 > -1.47 AND feature_1 < 0.03',
 'feature_0 < -1.3 AND feature_1 > -1.47 AND feature_1 < 0.53',
 'feature_0 < -1.3 AND feature_1 > -1.47 AND feature_1 < 1.03',
 'feature_0 < -1.3 AND feature_1 > -0.97 AND feature_1 < -0.47',
 'feature_0 < -1.3 AND feature_1 > -0.97 AND feature_1 < 0.03',
 'feature_0 < -1.3 AND feature_1 > -0.97 AND feature_1 < 0.53',
 'feature_0 < -1.3 AND feature_1 > -0.97 AND feature_1 < 1.03',
 'feature_0 < -1.3 AND feature_1 > -0.97 AND feature_1 < 1.53',
 'feature_0 < -1.3 AND feature_1 > -0.47 AND feature_1 < 0.03',
 'feature_0 < -1.3 AND feature_1 > -0.47 AND feature_1 < 0.53',
 'feature_0 < -1.3 AND feature_1 > -0.47 AND feature_1 < 1.03',
 'feature_0 < -1.3 AND feature_1 > -0.47 AND feature_1 < 1.53',
 'feature_0 < -1.3 AND feature_1 > -0.47 AND feature_1 < 2.03',
 'feature_0 < -1.3 AND feature_1 > -0.47 AND feature_1 < 2.53',
 'feature_0 < -1.3 AND feature_1 > -0.47 AND feature_1 < 3.03',
 'feature_0 < -1.3 AND feature_1 > -0.47 AND feature_1 < 3.53',
 'feature_0 < -1.3 AND feature_1 > 0.03 AND feature_1 < 0.53',
 'feature_0 < -1.3 AND feature_1 > 0.03 AND feature_1 < 1.03',
 'feature_0 < -1.3 AND feature_1 > 0.03 AND feature_1 < 1.53',
 'feature_0 < -1.3 AND feature_1 > 0.03 AND feature_1 < 2.03',
 'feature_0 < -1.3 AND feature_1 > 0.03 AND feature_1 < 2.53',
 'feature_0 < -1.3 AND feature_1 > 0.03 AND feature_1 < 3.03',
 'feature_0 < -1.3 AND feature_1 > 0.03 AND feature_1 < 3.53',
 'feature_0 < -1.3 AND feature_1 > 0.53 AND feature_1 < 1.03',
 'feature_0 < -1.3 AND feature_1 > 0.53 AND feature_1 < 1.53',
 'feature_0 < -1.3 AND feature_1 > 0.53 AND feature_1 < 2.03',
 'feature_0 < -1.3 AND feature_1 > 0.53 AND feature_1 < 2.53',
 'feature_0 < -1.3 AND feature_1 > 0.53 AND feature_1 < 3.03',
 'feature_0 < -1.3 AND feature_1 > 0.53 AND feature_1 < 3.53',
 'feature_0 < -1.3 AND feature_1 > 1.03 AND feature_1 < 1.53',
 'feature_0 < -1.3 AND feature_1 > 1.03 AND feature_1 < 2.03',
 'feature_0 < -1.3 AND feature_1 > 1.03 AND feature_1 < 2.53',
 'feature_0 < -1.3 AND feature_1 > 1.03 AND feature_1 < 3.03',
 'feature_0 < -1.3 AND feature_1 > 1.03 AND feature_1 < 3.53',
 'feature_0 > -0.8 AND feature_1 < -2.47',
 'feature_0 > -0.8 AND feature_1 < -1.97',
 'feature_0 > -0.8 AND feature_1 < -1.47',
 'feature_0 > -0.8 AND feature_1 < -0.97',
 'feature_0 > -0.8 AND feature_1 > -0.47',
 'feature_0 > -0.8 AND feature_1 < -0.47',
 'feature_0 > -0.8 AND feature_1 > 0.03',
 'feature_0 > -0.8 AND feature_1 < 0.03',
 'feature_0 > -0.8 AND feature_1 > 0.53',
 'feature_0 > -0.8 AND feature_1 < 0.53',
 'feature_0 > -0.8 AND feature_1 > 1.03',
 'feature_0 > -0.8 AND feature_1 > 1.53',
 'feature_0 > -0.8 AND feature_1 > 2.03',
 'feature_0 > -0.8 AND feature_1 > -4.47 AND feature_1 < -2.47',
 'feature_0 > -0.8 AND feature_1 > -4.47 AND feature_1 < -1.97',
 'feature_0 > -0.8 AND feature_1 > -4.47 AND feature_1 < -1.47',
 'feature_0 > -0.8 AND feature_1 > -4.47 AND feature_1 < -0.97',
 'feature_0 > -0.8 AND feature_1 > -4.47 AND feature_1 < -0.47',
 'feature_0 > -0.8 AND feature_1 > -4.47 AND feature_1 < 0.03',
 'feature_0 > -0.8 AND feature_1 > -4.47 AND feature_1 < 0.53',
 'feature_0 > -0.8 AND feature_1 > -3.97 AND feature_1 < -2.47',
 'feature_0 > -0.8 AND feature_1 > -3.97 AND feature_1 < -1.97',
 'feature_0 > -0.8 AND feature_1 > -3.97 AND feature_1 < -1.47',
 'feature_0 > -0.8 AND feature_1 > -3.97 AND feature_1 < -0.97',
 'feature_0 > -0.8 AND feature_1 > -3.97 AND feature_1 < -0.47',
 'feature_0 > -0.8 AND feature_1 > -3.97 AND feature_1 < 0.03',
 'feature_0 > -0.8 AND feature_1 > -3.97 AND feature_1 < 0.53',
 'feature_0 > -0.8 AND feature_1 > -3.47 AND feature_1 < -1.97',
 'feature_0 > -0.8 AND feature_1 > -3.47 AND feature_1 < -1.47',
 'feature_0 > -0.8 AND feature_1 > -3.47 AND feature_1 < -0.97',
 'feature_0 > -0.8 AND feature_1 > -3.47 AND feature_1 < -0.47',